version: '3'
services: 
    redis-server:
      image: 'redis' 
    flask-app:
      restart: always
      build: .
      ports:
          - "8081:5000"
      environment:
        - REDIS_HOST=redis-server 

